using System.Text;
using Apex.Ledger;
using Apex.Ledger.Domain;
using Apex.Ledger.Io;
using Apex.Ledger.Reports;
using Apex.Ledger.Services;
using Xunit;

namespace Apex.Ledger.Io.Tests;

/// <summary>
/// Phase-8 slice-4 <b>ECR 2.0 writer</b> contract (RQ-9) — the hand-rolled <c>#~#</c>-delimited EPFO offline
/// flat-file. Asserts the exact member field order/values (the brief's sample line) and the establishment challan
/// account-head totals, that the writer is deterministic + byte-stable, and that a builder-produced return
/// reconciles to the same figures the payroll voucher posts.
/// </summary>
public sealed class EcrWriterTests
{
    private static readonly DateOnly From = new(2025, 4, 1);
    private static readonly DateOnly To = new(2025, 4, 30);

    [Fact]
    public void A_member_line_matches_the_ecr_field_order_with_no_challan_trailer()
    {
        // A capped ₹20,000 earner (no higher-wage opt-in): EPF/EPS/EDLI wages 15,000; EE 1,800 / EPS 1,250 / ER 550.
        var member = new PfEcrMember(
            Uan: "100123456789", Name: "SANJAY KUMAR",
            GrossWages: 20000, EpfWages: 15000, EpsWages: 15000, EdliWages: 15000,
            EmployeeShareEpf: 1800, EpsContribution: 1250, EmployerShareEpf: 550,
            NcpDays: 0, RefundOfAdvances: 0);
        var ecr = new PfEcrReturn("MHBAN0000000000", To,
            new[] { member },
            new PfChallanTotals(Account1: 2350, Account2: 500, Account10: 1250, Account21: 75, Account22: 0));

        var text = Encoding.UTF8.GetString(EcrWriter.Write(ecr));
        var lines = text.Split('\n', StringSplitOptions.RemoveEmptyEntries);

        // The ECR 2.0 upload file is member-detail lines ONLY — the challan (A/c 1/2/10/21/22) is auto-generated by
        // the EPFO portal after upload and must NOT be embedded as a line, or the per-line ECR validation rejects it.
        var line = Assert.Single(lines);
        Assert.Equal("100123456789#~#SANJAY KUMAR#~#20000#~#15000#~#15000#~#15000#~#1800#~#1250#~#550#~#0#~#0", line);
        Assert.DoesNotContain(lines, l => l.StartsWith("CHALLAN", StringComparison.Ordinal));

        // The challan account-head totals remain available on the return (the on-screen / separate summary), never
        // in the file.
        Assert.Equal(2350, ecr.Totals.Account1);
        Assert.Equal(500, ecr.Totals.Account2);

        // Deterministic + byte-stable.
        Assert.Equal(EcrWriter.Write(ecr), EcrWriter.Write(ecr));
    }

    // ---------------------------------------------------------------- finding-1 regression: no CHALLAN trailer

    [Fact]
    public void The_exported_ecr_file_is_member_lines_only_keyed_by_a_12_digit_uan()
    {
        var (c, empId) = BuildPfCompany(basic: 20000m, higherWageOptIn: false);
        var ecr = PfEcr.Build(c, new[] { empId }, From, To);

        var lines = Encoding.UTF8.GetString(EcrWriter.Write(ecr))
            .Split('\n', StringSplitOptions.RemoveEmptyEntries);

        // Exactly one line — the single member; no non-conformant challan trailer.
        Assert.Single(lines);
        Assert.DoesNotContain(lines, l => l.StartsWith("CHALLAN", StringComparison.Ordinal));
        // Every emitted line is a member record whose first field is a valid 12-digit UAN (EPFO per-line validation).
        foreach (var l in lines)
            Assert.Matches(@"^\d{12}$", l.Split("#~#")[0]);
    }

    // ---------------------------------------------------------------- finding-2/3 regression: company uncap default

    [Fact]
    public void A_company_that_does_not_cap_by_default_reports_uncapped_epf_wages_on_the_ecr()
    {
        // Establishment default = do NOT cap (CapWagesAtCeiling=false); member did NOT opt in per-employee. The
        // company default must still uncap EPF wages (the per-employee opt-in only overrides the company default).
        var (c, empId) = BuildPfCompany(basic: 25000m, higherWageOptIn: false, capWagesAtCeiling: false);
        var m = Assert.Single(PfEcr.Build(c, new[] { empId }, From, To).Members);

        Assert.Equal(25000, m.EpfWages);        // uncapped by the company default (would be 15,000 if the flag were inert)
        Assert.Equal(3000, m.EmployeeShareEpf); // 12% × 25,000
        Assert.Equal(1250, m.EpsContribution);  // EPS still capped (8.33% × 15,000, cap 1,250)
        Assert.Equal(1750, m.EmployerShareEpf); // 3,000 − 1,250 (anti-3.67% residual)
        Assert.Equal(15000, m.EpsWages);
        Assert.Equal(15000, m.EdliWages);
        Assert.Equal(m.EmployeeShareEpf, m.EpsContribution + m.EmployerShareEpf); // EPS + ER == EE invariant
    }

    // ---------------------------------------------------------------- finding-4 regression: ECR rejects a bad UAN

    [Fact]
    public void PfEcr_build_rejects_a_pf_member_whose_uan_is_not_12_digits()
    {
        var (c, empId) = BuildPfCompany(basic: 15000m, higherWageOptIn: false);
        // Corrupt the source directly (bypassing the service guard) to a present-but-malformed UAN — a state only an
        // imported / hand-edited company could reach. The ECR must reject it rather than emit an EPFO-invalid line.
        c.FindEmployee(empId)!.Uan = "12345";
        Assert.Throws<InvalidOperationException>(() => PfEcr.Build(c, new[] { empId }, From, To));
    }

    [Fact]
    public void The_builder_reconciles_to_the_payroll_computation()
    {
        var (c, empId) = BuildPfCompany(basic: 20000m, higherWageOptIn: false);

        var ecr = PfEcr.Build(c, new[] { empId }, From, To);
        var m = Assert.Single(ecr.Members);

        Assert.Equal("100123456789", m.Uan);
        Assert.Equal(20000, m.GrossWages);
        Assert.Equal(15000, m.EpfWages);
        Assert.Equal(15000, m.EpsWages);
        Assert.Equal(15000, m.EdliWages);
        Assert.Equal(1800, m.EmployeeShareEpf);
        Assert.Equal(1250, m.EpsContribution);
        Assert.Equal(550, m.EmployerShareEpf);

        // Challan totals reconcile: A/c 1 = 1,800 + 550 = 2,350; A/c 2 floored to 500; A/c 10 = 1,250; A/c 21 = 75; A/c 22 = 0.
        Assert.Equal(2350, ecr.Totals.Account1);
        Assert.Equal(500, ecr.Totals.Account2);
        Assert.Equal(1250, ecr.Totals.Account10);
        Assert.Equal(75, ecr.Totals.Account21);
        Assert.Equal(0, ecr.Totals.Account22);

        // And the writer emits the exact ECR line for the built member.
        var lines = Encoding.UTF8.GetString(EcrWriter.Write(ecr)).Split('\n', StringSplitOptions.RemoveEmptyEntries);
        Assert.Equal("100123456789#~#Sanjay Kumar#~#20000#~#15000#~#15000#~#15000#~#1800#~#1250#~#550#~#0#~#0", lines[0]);
    }

    private static (Company Company, Guid EmployeeId) BuildPfCompany(
        decimal basic, bool higherWageOptIn, bool capWagesAtCeiling = true)
    {
        var c = CompanyFactory.CreateSeeded("ECR Co", From, From);
        var pay = new PayrollService(c);
        pay.EnablePayroll();
        pay.EnableProvidentFund(capWagesAtCeiling: capWagesAtCeiling);
        var ph = new PayHeadService(c);
        var indirect = c.FindGroupByName("Indirect Expenses")!.Id;
        var liab = c.FindGroupByName("Current Liabilities")!.Id;

        var basicHead = ph.CreatePayHead("Basic", PayHeadType.Earnings, PayHeadCalculationType.FlatRate,
            underGroupId: indirect, partOfPfWages: true);
        var ee = ph.CreatePayHead("Employee EPF", PayHeadType.EmployeesStatutoryDeductions,
            PayHeadCalculationType.AsUserDefinedValue, underGroupId: liab,
            pfComponent: PfStatutoryComponent.EmployeeProvidentFund);
        var er = ph.CreatePayHead("Employer EPF", PayHeadType.EmployersStatutoryContributions,
            PayHeadCalculationType.AsUserDefinedValue, underGroupId: liab,
            pfComponent: PfStatutoryComponent.EmployerProvidentFund);
        var eps = ph.CreatePayHead("Employer Pension", PayHeadType.EmployersStatutoryContributions,
            PayHeadCalculationType.AsUserDefinedValue, underGroupId: liab,
            pfComponent: PfStatutoryComponent.EmployerPension);
        var edli = ph.CreatePayHead("EDLI", PayHeadType.EmployersOtherCharges,
            PayHeadCalculationType.AsUserDefinedValue, underGroupId: liab,
            pfComponent: PfStatutoryComponent.EmployeesDepositLinkedInsurance);

        var e = pay.CreateEmployee("Sanjay Kumar", pay.CreateEmployeeGroup("Staff").Id, uan: "100123456789");
        pay.SetEmployeePfDetails(e.Id, applicable: true, contributeOnHigherWages: higherWageOptIn);
        new SalaryStructureService(c).DefineForEmployee(e.Id, From, new[]
        {
            new SalaryStructureLine(basicHead.Id, 0, new Money(basic)),
            new SalaryStructureLine(ee.Id, 1),
            new SalaryStructureLine(er.Id, 2),
            new SalaryStructureLine(eps.Id, 3),
            new SalaryStructureLine(edli.Id, 4),
        });
        return (c, e.Id);
    }
}
