using System.Text;

namespace Apex.Ledger.Io;

/// <summary>
/// The four QR error-correction levels of ISO/IEC 18004, in the order the standard numbers them. The enum's
/// <b>declaration order is L, M, Q, H</b> (recovery capacity ~7 / 15 / 25 / 30 %), which is NOT the order of the
/// two-bit format-information code — see <see cref="QrCode.FormatBitsFor"/>, which holds the mapping in one place.
/// </summary>
public enum QrErrorCorrection
{
    /// <summary>Level L — recovers ~7% of codewords.</summary>
    Low,

    /// <summary>Level M — recovers ~15% of codewords.</summary>
    Medium,

    /// <summary>Level Q — recovers ~25% of codewords.</summary>
    Quartile,

    /// <summary>Level H — recovers ~30% of codewords.</summary>
    High,
}

/// <summary>
/// A rendered QR symbol: a square grid of light/dark modules, <b>excluding</b> the quiet zone (ISO/IEC 18004 §9.1
/// requires four modules of light margin, which the consumer adds — <see cref="PdfBitmap.FromQr"/> does).
/// </summary>
public sealed class QrCodeMatrix
{
    private readonly bool[] _modules;   // row-major, length Size*Size

    internal QrCodeMatrix(int version, int size, bool[] modules)
    {
        Version = version;
        Size = size;
        _modules = modules;
    }

    /// <summary>The symbol version, 1–40. The side length is <c>17 + 4 × Version</c> modules.</summary>
    public int Version { get; }

    /// <summary>The side length in modules (21 for version 1 … 177 for version 40).</summary>
    public int Size { get; }

    /// <summary>True when the module at column <paramref name="x"/>, row <paramref name="y"/> is dark (printed).
    /// Coordinates outside the symbol read light, so a consumer may over-scan into the quiet zone.</summary>
    public bool IsDark(int x, int y) =>
        x >= 0 && y >= 0 && x < Size && y < Size && _modules[y * Size + x];
}

/// <summary>
/// A <b>dependency-free QR Code encoder</b> (ISO/IEC 18004), written in-tree because this repository builds with no
/// external packages. Byte-mode only — which is exactly and only what this product needs: the artefact it has to
/// print is the IRP's signed QR string, a JWS of base64url characters and two dots.
///
/// <para><b>Why an encoder is not a "credential" problem (ER-5).</b> This class encodes a string that was handed to
/// us; it computes no IRN and signs nothing. It is a <i>rendering</i> of an artefact the IRP already produced, in the
/// same sense that <see cref="PdfWriter.Text"/> is a rendering of a number the ledger already posted. There is
/// deliberately no member here that takes invoice fields and builds a payload.</para>
///
/// <para><b>Determinism.</b> No clock, no RNG, no culture-sensitive formatting, no dictionary iteration order. The
/// mask is chosen by the standard's own penalty score with the lowest index winning a tie, so one input yields one
/// symbol, byte-for-byte, on every run and every machine.</para>
///
/// <para><b>Verification.</b> <c>QrCodeTests</c> compares whole module matrices against vectors generated by
/// <i>segno</i>, an independent pure-Python QR encoder that shares no code, no tables and no author with this one.
/// A self-consistent check (encode, then decode with our own reader) could not have caught a wrong table; an
/// independent encoder can, and did drive this file's tables.</para>
/// </summary>
public static class QrCode
{
    /// <summary>Byte-mode indicator (ISO/IEC 18004 Table 2). The only mode this encoder emits.</summary>
    private const int ByteModeIndicator = 0b0100;

    /// <summary>The lowest and highest symbol versions.</summary>
    public const int MinVersion = 1;
    public const int MaxVersion = 40;

    /// <summary>
    /// Encodes <paramref name="text"/> as a byte-mode QR symbol at the given error-correction level, choosing the
    /// smallest version that holds it.
    /// </summary>
    /// <exception cref="ArgumentException">The text does not fit in a version-40 symbol at this level.</exception>
    public static QrCodeMatrix Encode(string text, QrErrorCorrection ecc = QrErrorCorrection.Medium)
    {
        ArgumentNullException.ThrowIfNull(text);
        return Encode(Encoding.UTF8.GetBytes(text), ecc);
    }

    /// <summary>Encodes raw bytes as a byte-mode QR symbol at the given error-correction level.</summary>
    /// <exception cref="ArgumentException">The data does not fit in a version-40 symbol at this level.</exception>
    public static QrCodeMatrix Encode(byte[] data, QrErrorCorrection ecc = QrErrorCorrection.Medium) =>
        Encode(data, ecc, forcedMask: null);

    /// <summary>
    /// The encoder proper. <paramref name="forcedMask"/> is <c>null</c> in production — the mask is then chosen by the
    /// standard's penalty score. <b>It exists for the oracle test</b>, and that is not a detail: the ONLY part of this
    /// encoder an independent implementation may legitimately disagree about is <i>which</i> of the eight equally-valid
    /// masks it prefers (ISO/IEC 18004's rule-3 penalty is ambiguous about the quiet zone, and implementations differ).
    /// Pinning the mask removes that one degree of freedom, so <c>QrCodeTests</c> can compare WHOLE MATRICES against an
    /// independent encoder and have every disagreement be a real defect. Comparing only auto-mask output would have
    /// forced the test to tolerate differences, and a tolerant comparison is what lets a wrong table through.
    /// </summary>
    internal static QrCodeMatrix Encode(byte[] data, QrErrorCorrection ecc, int? forcedMask)
    {
        ArgumentNullException.ThrowIfNull(data);
        if (forcedMask is < 0 or > 7) throw new ArgumentOutOfRangeException(nameof(forcedMask));

        int version = ChooseVersion(data.Length, ecc);
        int dataCodewords = DataCodewordCount(version, ecc);

        // ---- bit stream: mode + character count + payload + terminator + byte-align + pad codewords ----
        var bits = new BitBuffer(dataCodewords * 8);
        bits.Append(ByteModeIndicator, 4);
        bits.Append(data.Length, CharCountBits(version));
        foreach (byte b in data) bits.Append(b, 8);

        int capacityBits = dataCodewords * 8;
        bits.Append(0, Math.Min(4, capacityBits - bits.Length));              // terminator
        bits.Append(0, (8 - bits.Length % 8) % 8);                            // byte-align
        for (int pad = 0xEC; bits.Length < capacityBits; pad ^= 0xEC ^ 0x11)  // 11101100 / 00010001, alternating
            bits.Append(pad, 8);

        byte[] codewords = AddErrorCorrection(bits.ToBytes(), version, ecc);

        // ---- draw ----
        var canvas = new Canvas(version);
        canvas.DrawFunctionPatterns();
        canvas.DrawCodewords(codewords);

        int bestMask = forcedMask ?? 0;
        if (forcedMask is null)
        {
            long bestPenalty = long.MaxValue;
            for (int mask = 0; mask < 8; mask++)
            {
                canvas.ApplyMask(mask);
                canvas.DrawFormatBits(ecc, mask);
                long penalty = canvas.PenaltyScore();
                if (penalty < bestPenalty) { bestPenalty = penalty; bestMask = mask; }
                canvas.ApplyMask(mask);   // XOR is its own inverse — undo
            }
        }
        canvas.ApplyMask(bestMask);
        canvas.DrawFormatBits(ecc, bestMask);

        return canvas.ToMatrix();
    }

    // ================================================================ capacity

    /// <summary>The smallest version whose data capacity at <paramref name="ecc"/> holds <paramref name="byteCount"/>
    /// bytes in byte mode.</summary>
    public static int ChooseVersion(int byteCount, QrErrorCorrection ecc)
    {
        if (byteCount < 0) throw new ArgumentOutOfRangeException(nameof(byteCount));
        for (int v = MinVersion; v <= MaxVersion; v++)
        {
            // 4 mode bits + the version's character-count field + 8 bits per byte.
            long needed = 4 + CharCountBits(v) + 8L * byteCount;
            if (needed <= DataCodewordCount(v, ecc) * 8L) return v;
        }
        throw new ArgumentException(
            $"{byteCount} bytes do not fit in a version-{MaxVersion} QR symbol at error-correction level {ecc}.",
            nameof(byteCount));
    }

    /// <summary>The width of the byte-mode character-count indicator (ISO/IEC 18004 Table 3).</summary>
    private static int CharCountBits(int version) => version <= 9 ? 8 : 16;

    /// <summary>
    /// The number of module positions a symbol has available for data + EC codewords, i.e. every module except the
    /// function patterns (finders, separators, timing, alignment, format and version areas, dark module). Computed
    /// rather than tabulated so it cannot disagree with <see cref="AlignmentPatternPositions"/>.
    /// </summary>
    private static int RawDataModules(int version)
    {
        int result = (16 * version + 128) * version + 64;
        if (version >= 2)
        {
            int numAlign = version / 7 + 2;
            result -= (25 * numAlign - 10) * numAlign - 55;   // alignment patterns, minus their timing overlaps
            if (version >= 7) result -= 36;                    // the two 6x3 version-information blocks
        }
        return result;
    }

    /// <summary>The number of DATA codewords (payload, before error correction) a version/level pair carries.</summary>
    public static int DataCodewordCount(int version, QrErrorCorrection ecc)
    {
        int e = (int)ecc;
        return RawDataModules(version) / 8
             - EccCodewordsPerBlock[e][version] * EccBlockCount[e][version];
    }

    // ================================================================ error correction

    /// <summary>Splits the data into the standard's blocks, appends each block's Reed–Solomon remainder, and
    /// interleaves the result into the final codeword sequence (ISO/IEC 18004 §8.6).</summary>
    private static byte[] AddErrorCorrection(byte[] data, int version, QrErrorCorrection ecc)
    {
        int e = (int)ecc;
        int numBlocks = EccBlockCount[e][version];
        int eccLen = EccCodewordsPerBlock[e][version];
        int rawCodewords = RawDataModules(version) / 8;
        int shortBlockLen = rawCodewords / numBlocks - eccLen;      // data codewords in a SHORT block
        int numShortBlocks = numBlocks - rawCodewords % numBlocks;  // the rest are one codeword longer

        var generator = ReedSolomonGenerator(eccLen);
        var blocks = new List<byte[]>(numBlocks);
        for (int i = 0, k = 0; i < numBlocks; i++)
        {
            int len = shortBlockLen + (i < numShortBlocks ? 0 : 1);
            var dat = new byte[len];
            Array.Copy(data, k, dat, 0, len);
            k += len;
            var block = new byte[len + eccLen];
            Array.Copy(dat, block, len);
            Array.Copy(ReedSolomonRemainder(dat, generator), 0, block, len, eccLen);
            blocks.Add(block);
        }

        var result = new byte[rawCodewords];
        int w = 0;
        // Interleave the data codewords column-wise; a short block contributes nothing to the last data column.
        for (int i = 0; i <= shortBlockLen; i++)
            for (int b = 0; b < blocks.Count; b++)
                if (i != shortBlockLen || b >= numShortBlocks)
                    result[w++] = blocks[b][i];
        // Then the EC codewords, which are the same length in every block.
        for (int i = 0; i < eccLen; i++)
            for (int b = 0; b < blocks.Count; b++)
                result[w++] = blocks[b][blocks[b].Length - eccLen + i];
        return result;
    }

    /// <summary>The degree-<paramref name="degree"/> Reed–Solomon generator polynomial over GF(2^8), coefficients in
    /// descending order and the leading 1 omitted.</summary>
    private static byte[] ReedSolomonGenerator(int degree)
    {
        var result = new byte[degree];
        result[degree - 1] = 1;
        byte root = 1;
        for (int i = 0; i < degree; i++)
        {
            for (int j = 0; j < degree; j++)
            {
                result[j] = GfMultiply(result[j], root);
                if (j + 1 < degree) result[j] ^= result[j + 1];
            }
            root = GfMultiply(root, 0x02);
        }
        return result;
    }

    /// <summary>The remainder of <paramref name="data"/> divided by the generator — the block's EC codewords.</summary>
    private static byte[] ReedSolomonRemainder(byte[] data, byte[] generator)
    {
        var result = new byte[generator.Length];
        foreach (byte b in data)
        {
            byte factor = (byte)(b ^ result[0]);
            Array.Copy(result, 1, result, 0, result.Length - 1);
            result[^1] = 0;
            for (int i = 0; i < result.Length; i++)
                result[i] ^= GfMultiply(generator[i], factor);
        }
        return result;
    }

    /// <summary>Multiplication in GF(2^8) modulo the QR primitive polynomial x^8+x^4+x^3+x^2+1 (0x11D).</summary>
    private static byte GfMultiply(byte x, byte y)
    {
        int z = 0;
        for (int i = 7; i >= 0; i--)
        {
            z = (z << 1) ^ ((z >>> 7) * 0x11D);
            z ^= ((y >>> i) & 1) * x;
        }
        return (byte)z;
    }

    // ================================================================ format / version information

    /// <summary>
    /// The two-bit error-correction indicator used in the format information (ISO/IEC 18004 Table 12). <b>This is not
    /// the enum's ordinal</b> — the standard numbers the levels M=0, L=1, H=2, Q=3, while the enum is declared in
    /// capacity order L, M, Q, H. Kept in exactly one place so the two orders cannot be confused at a call site.
    /// </summary>
    internal static int FormatBitsFor(QrErrorCorrection ecc) => ecc switch
    {
        QrErrorCorrection.Medium => 0,
        QrErrorCorrection.Low => 1,
        QrErrorCorrection.High => 2,
        QrErrorCorrection.Quartile => 3,
        _ => throw new ArgumentOutOfRangeException(nameof(ecc)),
    };

    // ================================================================ the standard's two tables

    // ISO/IEC 18004 Table 13-22. Index [level][version]; index 0 of each row is unused (there is no version 0).
    // DRIVEN AND VERIFIED against the independent `segno` encoder — see QrCodeTests.
    private static readonly int[][] EccCodewordsPerBlock =
    {
        // L
        new[] { -1, 7, 10, 15, 20, 26, 18, 20, 24, 30, 18, 20, 24, 26, 30, 22, 24, 28, 30, 28, 28, 28, 28, 30, 30, 26, 28, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30 },
        // M
        new[] { -1, 10, 16, 26, 18, 24, 16, 18, 22, 22, 26, 30, 22, 22, 24, 24, 28, 28, 26, 26, 26, 26, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28 },
        // Q
        new[] { -1, 13, 22, 18, 26, 18, 24, 18, 22, 20, 24, 28, 26, 24, 20, 30, 24, 28, 28, 26, 30, 28, 30, 30, 30, 30, 28, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30 },
        // H
        new[] { -1, 17, 28, 22, 16, 22, 28, 26, 26, 24, 28, 24, 28, 22, 24, 24, 30, 28, 28, 26, 28, 30, 24, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30 },
    };

    private static readonly int[][] EccBlockCount =
    {
        // L
        new[] { -1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 4, 4, 4, 4, 4, 6, 6, 6, 6, 7, 8, 8, 9, 9, 10, 12, 12, 12, 13, 14, 15, 16, 17, 18, 19, 19, 20, 21, 22, 24, 25 },
        // M
        new[] { -1, 1, 1, 1, 2, 2, 4, 4, 4, 5, 5, 5, 8, 9, 9, 10, 10, 11, 13, 14, 16, 17, 17, 18, 20, 21, 23, 25, 26, 28, 29, 31, 33, 35, 37, 38, 40, 43, 45, 47, 49 },
        // Q
        new[] { -1, 1, 1, 2, 2, 4, 4, 6, 6, 8, 8, 8, 10, 12, 16, 12, 17, 16, 18, 21, 20, 23, 23, 25, 27, 29, 34, 34, 35, 38, 40, 43, 45, 48, 51, 53, 56, 59, 62, 65, 68 },
        // H
        new[] { -1, 1, 1, 2, 4, 4, 4, 5, 6, 8, 8, 11, 11, 16, 16, 18, 16, 19, 21, 25, 25, 25, 34, 30, 32, 35, 37, 40, 42, 45, 48, 51, 54, 57, 60, 63, 66, 70, 74, 77, 81 },
    };

    /// <summary>The centre coordinates of the alignment patterns for a version (ISO/IEC 18004 §6.3.6 / Annex E).
    /// Computed from the standard's rule rather than tabulated.</summary>
    internal static int[] AlignmentPatternPositions(int version)
    {
        if (version == 1) return Array.Empty<int>();
        int numAlign = version / 7 + 2;
        // The spacing is even and as large as possible; version 32 is the documented irregular case.
        int step = version == 32 ? 26 : (version * 4 + numAlign * 2 + 1) / (numAlign * 2 - 2) * 2;
        var result = new int[numAlign];
        result[0] = 6;
        for (int i = numAlign - 1, pos = version * 4 + 10; i >= 1; i--, pos -= step)
            result[i] = pos;
        return result;
    }

    // ================================================================ bit buffer

    /// <summary>An append-only MSB-first bit stream.</summary>
    private sealed class BitBuffer
    {
        private readonly List<byte> _bytes;
        private int _bitLength;

        public BitBuffer(int expectedBits) => _bytes = new List<byte>(expectedBits / 8 + 1);

        public int Length => _bitLength;

        public void Append(int value, int width)
        {
            for (int i = width - 1; i >= 0; i--)
            {
                if (_bitLength % 8 == 0) _bytes.Add(0);
                if (((value >>> i) & 1) != 0) _bytes[^1] |= (byte)(1 << (7 - _bitLength % 8));
                _bitLength++;
            }
        }

        public byte[] ToBytes() => _bytes.ToArray();
    }

    // ================================================================ the module canvas

    /// <summary>The symbol under construction: the modules plus the "this is a function pattern" mask that keeps the
    /// data walk and the XOR mask off the finders, timing and format areas.</summary>
    private sealed class Canvas
    {
        private readonly int _version;
        private readonly int _size;
        private readonly bool[] _modules;
        private readonly bool[] _isFunction;

        public Canvas(int version)
        {
            _version = version;
            _size = version * 4 + 17;
            _modules = new bool[_size * _size];
            _isFunction = new bool[_size * _size];
        }

        private bool Get(int x, int y) => _modules[y * _size + x];
        private void Set(int x, int y, bool dark) => _modules[y * _size + x] = dark;

        private void SetFunction(int x, int y, bool dark)
        {
            if (x < 0 || y < 0 || x >= _size || y >= _size) return;
            _modules[y * _size + x] = dark;
            _isFunction[y * _size + x] = true;
        }

        public QrCodeMatrix ToMatrix() => new(_version, _size, (bool[])_modules.Clone());

        public void DrawFunctionPatterns()
        {
            // Timing patterns (row 6 and column 6), alternating from the origin.
            for (int i = 0; i < _size; i++)
            {
                SetFunction(6, i, i % 2 == 0);
                SetFunction(i, 6, i % 2 == 0);
            }

            // Three finder patterns with their separators.
            DrawFinder(3, 3);
            DrawFinder(_size - 4, 3);
            DrawFinder(3, _size - 4);

            // Alignment patterns, skipping the three that would collide with a finder.
            var pos = AlignmentPatternPositions(_version);
            for (int i = 0; i < pos.Length; i++)
                for (int j = 0; j < pos.Length; j++)
                {
                    bool topLeft = i == 0 && j == 0;
                    bool topRight = i == 0 && j == pos.Length - 1;
                    bool bottomLeft = i == pos.Length - 1 && j == 0;
                    if (topLeft || topRight || bottomLeft) continue;
                    DrawAlignment(pos[j], pos[i]);
                }

            // Reserve the format area (drawn for real later) and the version area.
            DrawFormatBits(QrErrorCorrection.Low, 0);
            DrawVersionBits();
        }

        private void DrawFinder(int cx, int cy)
        {
            for (int dy = -4; dy <= 4; dy++)
                for (int dx = -4; dx <= 4; dx++)
                {
                    int dist = Math.Max(Math.Abs(dx), Math.Abs(dy));   // Chebyshev ring index
                    SetFunction(cx + dx, cy + dy, dist != 2 && dist <= 3);
                }
        }

        private void DrawAlignment(int cx, int cy)
        {
            for (int dy = -2; dy <= 2; dy++)
                for (int dx = -2; dx <= 2; dx++)
                    SetFunction(cx + dx, cy + dy, Math.Max(Math.Abs(dx), Math.Abs(dy)) != 1);
        }

        /// <summary>Writes the 15-bit format information (level + mask + BCH(15,5), XOR 0x5412) into both copies.</summary>
        public void DrawFormatBits(QrErrorCorrection ecc, int mask)
        {
            int data = FormatBitsFor(ecc) << 3 | mask;
            int rem = data;
            for (int i = 0; i < 10; i++) rem = (rem << 1) ^ ((rem >>> 9) * 0x537);
            int bits = (data << 10 | rem) ^ 0x5412;

            // First copy, around the top-left finder.
            for (int i = 0; i <= 5; i++) SetFunction(8, i, Bit(bits, i));
            SetFunction(8, 7, Bit(bits, 6));
            SetFunction(8, 8, Bit(bits, 7));
            SetFunction(7, 8, Bit(bits, 8));
            for (int i = 9; i < 15; i++) SetFunction(14 - i, 8, Bit(bits, i));

            // Second copy, split between the other two finders.
            for (int i = 0; i < 8; i++) SetFunction(_size - 1 - i, 8, Bit(bits, i));
            for (int i = 8; i < 15; i++) SetFunction(8, _size - 15 + i, Bit(bits, i));
            SetFunction(8, _size - 8, true);   // the always-dark module
        }

        /// <summary>Writes the 18-bit version information (version + BCH(18,6), no XOR) — versions 7 and up only.</summary>
        private void DrawVersionBits()
        {
            if (_version < 7) return;
            int rem = _version;
            for (int i = 0; i < 12; i++) rem = (rem << 1) ^ ((rem >>> 11) * 0x1F25);
            int bits = _version << 12 | rem;

            for (int i = 0; i < 18; i++)
            {
                bool bit = Bit(bits, i);
                int a = _size - 11 + i % 3;
                int b = i / 3;
                SetFunction(a, b, bit);
                SetFunction(b, a, bit);
            }
        }

        private static bool Bit(int value, int index) => ((value >>> index) & 1) != 0;

        /// <summary>Walks the interleaved codewords up and down the two-module-wide columns, right to left, skipping
        /// the vertical timing column and every function module (ISO/IEC 18004 §8.7.3).</summary>
        public void DrawCodewords(byte[] codewords)
        {
            int i = 0;   // bit index into codewords
            for (int right = _size - 1; right >= 1; right -= 2)
            {
                if (right == 6) right = 5;   // the vertical timing pattern is not part of a column pair
                for (int v = 0; v < _size; v++)
                    for (int j = 0; j < 2; j++)
                    {
                        int x = right - j;
                        bool upward = ((right + 1) & 2) == 0;
                        int y = upward ? _size - 1 - v : v;
                        if (_isFunction[y * _size + x] || i >= codewords.Length * 8) continue;
                        Set(x, y, ((codewords[i >>> 3] >>> (7 - (i & 7))) & 1) != 0);
                        i++;
                    }
            }
        }

        /// <summary>XORs the given data-mask pattern over every non-function module. Self-inverse.</summary>
        public void ApplyMask(int mask)
        {
            for (int y = 0; y < _size; y++)
                for (int x = 0; x < _size; x++)
                {
                    if (_isFunction[y * _size + x]) continue;
                    bool invert = mask switch
                    {
                        0 => (x + y) % 2 == 0,
                        1 => y % 2 == 0,
                        2 => x % 3 == 0,
                        3 => (x + y) % 3 == 0,
                        4 => (x / 3 + y / 2) % 2 == 0,
                        5 => x * y % 2 + x * y % 3 == 0,
                        6 => (x * y % 2 + x * y % 3) % 2 == 0,
                        7 => ((x + y) % 2 + x * y % 3) % 2 == 0,
                        _ => throw new ArgumentOutOfRangeException(nameof(mask)),
                    };
                    if (invert) _modules[y * _size + x] ^= true;
                }
        }

        /// <summary>The four penalty rules of ISO/IEC 18004 §8.8.2, summed. The mask with the lowest total wins.</summary>
        public long PenaltyScore()
        {
            const int N1 = 3, N2 = 3, N3 = 40, N4 = 10;
            long result = 0;

            // Rule 1 — runs of five or more same-coloured modules in a row / column.
            for (int y = 0; y < _size; y++)
            {
                bool colour = Get(0, y);
                int run = 1;
                for (int x = 1; x < _size; x++)
                {
                    if (Get(x, y) == colour) { run++; if (run == 5) result += N1; else if (run > 5) result++; }
                    else { colour = Get(x, y); run = 1; }
                }
            }
            for (int x = 0; x < _size; x++)
            {
                bool colour = Get(x, 0);
                int run = 1;
                for (int y = 1; y < _size; y++)
                {
                    if (Get(x, y) == colour) { run++; if (run == 5) result += N1; else if (run > 5) result++; }
                    else { colour = Get(x, y); run = 1; }
                }
            }

            // Rule 2 — every 2x2 block of one colour.
            for (int y = 0; y < _size - 1; y++)
                for (int x = 0; x < _size - 1; x++)
                {
                    bool c = Get(x, y);
                    if (c == Get(x + 1, y) && c == Get(x, y + 1) && c == Get(x + 1, y + 1)) result += N2;
                }

            // Rule 3 — the 1:1:3:1:1 finder-like pattern with four light modules on either side.
            for (int y = 0; y < _size; y++)
                for (int x = 0; x < _size; x++)
                {
                    if (x + 6 < _size && IsFinderLike(x, y, horizontal: true)) result += N3;
                    if (y + 6 < _size && IsFinderLike(x, y, horizontal: false)) result += N3;
                }

            // Rule 4 — deviation of the dark-module proportion from 50%, in 5% steps.
            int dark = 0;
            foreach (bool m in _modules) if (m) dark++;
            int total = _size * _size;
            int k = (int)((Math.Abs(dark * 20L - total * 10L) + total - 1) / total) - 1;
            result += (long)k * N4;

            return result;
        }

        /// <summary>The 1:1:3:1:1 dark-light-dark ratio, preceded or followed by four light modules — the pattern a
        /// scanner would mistake for a finder.</summary>
        private bool IsFinderLike(int x, int y, bool horizontal)
        {
            bool At(int i) => horizontal ? Get(x + i, y) : Get(x, y + i);
            if (!(At(0) && !At(1) && At(2) && At(3) && At(4) && !At(5) && At(6))) return false;

            bool LightRun(int from, int count)
            {
                for (int i = from; i < from + count; i++)
                {
                    int px = horizontal ? x + i : x;
                    int py = horizontal ? y : y + i;
                    if (px < 0 || py < 0 || px >= _size || py >= _size) continue;   // outside == quiet zone == light
                    if (Get(px, py)) return false;
                }
                return true;
            }
            return LightRun(-4, 4) || LightRun(7, 4);
        }
    }
}
